name: Build and test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  test_generic:
    name: Test with generic asm
    strategy:
      matrix:
        toolchain:
          - 1.91.0
          - nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust
        uses: actions/cache@v4
        with:
          path: ~/.rustup
          key: rustup-${{ runner.os }}-${{ matrix.toolchain }}
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: cargo-${{ runner.os }}-${{ matrix.toolchain }}

      - run: rustup update ${{ matrix.toolchain }}
      - run: rustup default ${{ matrix.toolchain }}
      - run: rustup component add clippy
      - run: cargo clippy -- --deny warnings
        working-directory: avr-q
      - run: cargo clippy --tests -- --deny warnings
        working-directory: avr-q
      - run: cargo build --verbose
        working-directory: avr-q
      - run: cargo test --verbose
        working-directory: avr-q
      - if: matrix.toolchain == 'nightly'
        run: |
          rustup component add rust-src miri
          cargo miri test
        working-directory: avr-q

# vim: ts=2 sw=2 expandtab
